subscription_id      = "f800f678-35f3-4453-9d5f-1ce0831dada0"
resource_group_name = "rgSLOTSeusdev"
storage_account_name = "slotsrgdevartifacts"
container_name = "terraform-state"
key = "dev/environment.tfstate"